/* tslint:disable */
/* eslint-disable */
/**
 * Pricing API
 * Provides API level access to the Costgraph Services.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: contact@baselinehq.cloud
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base';

export interface GithubComBaselinehqGolangSharedTypesInstance {
    'availability_zone'?: string;
    'fallback_to_base_pricing'?: boolean;
    'id'?: string;
    'instance_type'?: string;
    'operating_system'?: string;
    'provider'?: GithubComBaselinehqGolangSharedTypesProvider;
    'region'?: string;
    'service'?: TypesService;
    'usage_type'?: GithubComBaselinehqGolangSharedTypesUsageType;
    'vm'?: GithubComBaselinehqGolangSharedTypesVM;
}



export const GithubComBaselinehqGolangSharedTypesProvider = {
    /**
    * 
    */
    GCP: 'GCP',
    /**
    * 
    */
    AWS: 'AWS',
    /**
    * 
    */
    DigitalOcean: 'DigitalOcean',
    /**
    * 
    */
    Azure: 'Azure',
    /**
    * 
    */
    Hetzner: 'Hetzner',
    /**
    * 
    */
    OVHCloud: 'OVHCloud',
    /**
    * Base provider for default pricing, no specific cloud provider
    */
    Base: 'Base',
} as const;

export type GithubComBaselinehqGolangSharedTypesProvider = typeof GithubComBaselinehqGolangSharedTypesProvider[keyof typeof GithubComBaselinehqGolangSharedTypesProvider];



export const GithubComBaselinehqGolangSharedTypesUsageType = {
    SPOT_PREEMPTIBLE: 'SPOT_PREEMPTIBLE',
    ONDEMAND: 'ONDEMAND',
    RESERVED: 'RESERVED',
    ONDEMAND_CUSTOM: 'ONDEMAND_CUSTOM',
    SPOT_PREEMPTIBLE_CUSTOM: 'SPOT_PREEMPTIBLE_CUSTOM',
    RESERVED_CUSTOM: 'RESERVED_CUSTOM',
    SOLE_TENANCY: 'SOLE_TENANCY',
    CUSTOM: 'CUSTOM',
    EXTENDED: 'EXTENDED',
} as const;

export type GithubComBaselinehqGolangSharedTypesUsageType = typeof GithubComBaselinehqGolangSharedTypesUsageType[keyof typeof GithubComBaselinehqGolangSharedTypesUsageType];


export interface GithubComBaselinehqGolangSharedTypesVM {
    'cpu_cores'?: number;
    'ram_gb'?: number;
}

export const GithubComBaselinehqPricingapiPkgTypesStatus = {
    Registered: 'Registered',
    Deleted: 'Deleted',
} as const;

export type GithubComBaselinehqPricingapiPkgTypesStatus = typeof GithubComBaselinehqPricingapiPkgTypesStatus[keyof typeof GithubComBaselinehqPricingapiPkgTypesStatus];


export interface HandlerErrorResponse {
    'error'?: string;
}
export interface ProviderConfig {
    'predicates'?: TypesPredicates;
    'provider'?: GithubComBaselinehqGolangSharedTypesProvider;
}


export interface SchemaComputePricingsRow {
    'architecture'?: string;
    'availability_zone'?: string;
    'cost_per_hour'?: number;
    'cpu_cores'?: number;
    'cpu_cores_cost_per_hour'?: number;
    'created_at'?: string;
    'id'?: string;
    'instance_type'?: string;
    'operating_system'?: string;
    'period_billing_hours'?: number;
    'provider'?: string;
    'ram_gb'?: number;
    'ram_gb_cost_per_hour'?: number;
    'raw_pricing_data'?: object;
    'region'?: string;
    'service'?: string;
    'tags'?: object;
    'updated_at'?: string;
    'usage_type'?: string;
}
export interface SchemaDiskPricingsRow {
    'availability_zone'?: string;
    'cost_per_gb_hour'?: number;
    'cost_per_iops_hour'?: number;
    'cost_per_throughput_mbps_hour'?: number;
    'created_at'?: string;
    'id'?: string;
    'max_capacity_gb'?: number;
    'max_iops'?: number;
    'max_throughput_mbps'?: number;
    'min_capacity_gb'?: number;
    'min_iops'?: number;
    'min_throughput_mbps'?: number;
    'period_billing_hours'?: number;
    'provider'?: string;
    'raw_pricing_data'?: object;
    'region'?: string;
    'service'?: string;
    'tags'?: object;
    'type'?: string;
    'updated_at'?: string;
    'usage_type'?: string;
}
export interface TypesComputeRequest {
    'include_metadata'?: boolean;
    'instance'?: GithubComBaselinehqGolangSharedTypesInstance;
    'predicates'?: TypesPredicates;
    'usage'?: GithubComBaselinehqGolangSharedTypesVM;
}
export interface TypesComputeResultsValueInner {
    'instance_pricing'?: SchemaComputePricingsRow;
    'savings'?: TypesSavings;
    'vm'?: GithubComBaselinehqGolangSharedTypesVM;
}
export interface TypesCustomDiskPriceRequest {
    'entries': Array<SchemaDiskPricingsRow>;
}
export interface TypesCustomDiskPricingResponse {
    'entries'?: Array<SchemaDiskPricingsRow>;
    'status'?: GithubComBaselinehqPricingapiPkgTypesStatus;
}


export interface TypesCustomPriceRequest {
    'entries': Array<SchemaComputePricingsRow>;
}
export interface TypesCustomPricingResponse {
    'entries'?: Array<SchemaComputePricingsRow>;
    'status'?: GithubComBaselinehqPricingapiPkgTypesStatus;
}


export interface TypesDisk {
    'availability_zone'?: string;
    'capacity_gb'?: number;
    'fallback_to_base_pricing'?: boolean;
    'id'?: string;
    'iops'?: number;
    'provider'?: GithubComBaselinehqGolangSharedTypesProvider;
    'region'?: string;
    'service'?: TypesService;
    'throughput_mbps'?: number;
    'type'?: string;
    'usage_type'?: GithubComBaselinehqGolangSharedTypesUsageType;
}


export interface TypesDiskRequest {
    'include_metadata'?: boolean;
    'instance'?: TypesDisk;
    'predicates'?: TypesPredicates;
    'usage'?: TypesDisk;
}
export interface TypesDiskResultsValueInner {
    'disk'?: SchemaDiskPricingsRow;
    'disk_pricing'?: SchemaDiskPricingsRow;
    'savings'?: TypesSavings;
}
export interface TypesMarketplaceDiskProvidersResponse {
    'providers'?: Array<SchemaDiskPricingsRow>;
}
export interface TypesMarketplaceProvidersResponse {
    'providers'?: Array<SchemaComputePricingsRow>;
}
export interface TypesPredicates {
    'availability_zones'?: Array<string>;
    'disk_types'?: Array<string>;
    'instance_types'?: Array<string>;
    'operating_systems'?: Array<string>;
    'providers'?: Array<string>;
    'regions'?: Array<string>;
    'services'?: Array<string>;
    'usage_types'?: Array<string>;
}
export interface TypesSavings {
    'amount_per_hour'?: number;
    'amount_per_month'?: number;
    'amount_per_year'?: number;
    'percentage'?: number;
}

export const TypesService = {
    ComputeEngine: 'ComputeEngine',
    AmazonEC2: 'AmazonEC2',
    Droplet: 'Droplet',
    AzureCompute: 'AzureCompute',
    AzureManagedDisks: 'AzureManagedDisks',
    HetznerCompute: 'HetznerCompute',
    OVHPublicCloud: 'OVHPublicCloud',
    BaseCompute: 'BaseCompute',
    BaseDisks: 'BaseDisks',
    AmazonEBS: 'AmazonEBS',
    ComputeEnginePersistentDisk: 'ComputeEnginePersistentDisk',
} as const;

export type TypesService = typeof TypesService[keyof typeof TypesService];



/**
 * DefaultApi - axios parameter creator
 */
export const DefaultApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Health check endpoint
         * @summary Health check endpoint
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        healthzGet: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/healthz`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Delete a custom provider instance
         * @summary Delete a custom provider instance
         * @param {string} id Instance ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        marketplaceProvidersComputeDelete: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('marketplaceProvidersComputeDelete', 'id', id)
            const localVarPath = `/marketplace/providers/compute`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication ApiKeyAuth required
            await setApiKeyToObject(localVarHeaderParameter, "X-API-Key", configuration)

            // authentication BearerAuth required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)

            if (id !== undefined) {
                localVarQueryParameter['id'] = id;
            }

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Get your custom pricing entries
         * @summary Get your custom pricing entries
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        marketplaceProvidersComputeGet: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/marketplace/providers/compute`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication ApiKeyAuth required
            await setApiKeyToObject(localVarHeaderParameter, "X-API-Key", configuration)

            // authentication BearerAuth required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Register a custom provider
         * @summary Register a custom provider
         * @param {TypesCustomPriceRequest} instance Custom pricing request
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        marketplaceProvidersComputePost: async (instance: TypesCustomPriceRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'instance' is not null or undefined
            assertParamExists('marketplaceProvidersComputePost', 'instance', instance)
            const localVarPath = `/marketplace/providers/compute`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication ApiKeyAuth required
            await setApiKeyToObject(localVarHeaderParameter, "X-API-Key", configuration)

            // authentication BearerAuth required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(instance, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Delete a custom disk provider entry
         * @summary Delete a custom disk provider entry
         * @param {string} id Disk pricing ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        marketplaceProvidersDisksDelete: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('marketplaceProvidersDisksDelete', 'id', id)
            const localVarPath = `/marketplace/providers/disks`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication ApiKeyAuth required
            await setApiKeyToObject(localVarHeaderParameter, "X-API-Key", configuration)

            // authentication BearerAuth required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)

            if (id !== undefined) {
                localVarQueryParameter['id'] = id;
            }

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Get your custom disk pricing entries
         * @summary Get your custom disk pricing entries
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        marketplaceProvidersDisksGet: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/marketplace/providers/disks`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication ApiKeyAuth required
            await setApiKeyToObject(localVarHeaderParameter, "X-API-Key", configuration)

            // authentication BearerAuth required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Register a custom disk provider
         * @summary Register a custom disk provider
         * @param {TypesCustomDiskPriceRequest} instance Custom disk pricing request
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        marketplaceProvidersDisksPost: async (instance: TypesCustomDiskPriceRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'instance' is not null or undefined
            assertParamExists('marketplaceProvidersDisksPost', 'instance', instance)
            const localVarPath = `/marketplace/providers/disks`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication ApiKeyAuth required
            await setApiKeyToObject(localVarHeaderParameter, "X-API-Key", configuration)

            // authentication BearerAuth required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(instance, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Get pricing for compute instances
         * @summary Get pricing for an instance
         * @param {GithubComBaselinehqGolangSharedTypesInstance} instance Instance
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        pricingComputePost: async (instance: GithubComBaselinehqGolangSharedTypesInstance, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'instance' is not null or undefined
            assertParamExists('pricingComputePost', 'instance', instance)
            const localVarPath = `/pricing/compute`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication ApiKeyAuth required
            await setApiKeyToObject(localVarHeaderParameter, "X-API-Key", configuration)

            // authentication BearerAuth required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(instance, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Get pricing for a disk
         * @summary Get pricing for a disk
         * @param {TypesDisk} instance Disk
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        pricingDisksPost: async (instance: TypesDisk, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'instance' is not null or undefined
            assertParamExists('pricingDisksPost', 'instance', instance)
            const localVarPath = `/pricing/disks`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication ApiKeyAuth required
            await setApiKeyToObject(localVarHeaderParameter, "X-API-Key", configuration)

            // authentication BearerAuth required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(instance, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Get pricing for compute instances
         * @summary Get pricing for an instance
         * @param {GithubComBaselinehqGolangSharedTypesInstance} instance Instance
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        pricingPost: async (instance: GithubComBaselinehqGolangSharedTypesInstance, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'instance' is not null or undefined
            assertParamExists('pricingPost', 'instance', instance)
            const localVarPath = `/pricing`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication ApiKeyAuth required
            await setApiKeyToObject(localVarHeaderParameter, "X-API-Key", configuration)

            // authentication BearerAuth required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(instance, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Get details for the providers
         * @summary Get details for the providers
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        providersGet: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/providers`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication ApiKeyAuth required
            await setApiKeyToObject(localVarHeaderParameter, "X-API-Key", configuration)

            // authentication BearerAuth required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Get recommendations for compute instances (Recommendations, InstancePricing, VM, Savings)
         * @summary Get recommendations for compute instances
         * @param {TypesComputeRequest} instance Instance
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        recommendationsComputePost: async (instance: TypesComputeRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'instance' is not null or undefined
            assertParamExists('recommendationsComputePost', 'instance', instance)
            const localVarPath = `/recommendations/compute`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication ApiKeyAuth required
            await setApiKeyToObject(localVarHeaderParameter, "X-API-Key", configuration)

            // authentication BearerAuth required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(instance, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Get recommendations for disks used in the server (Recommendations, DiskPricing, Savings)
         * @summary Get recommendations for disks
         * @param {TypesDiskRequest} instance Instance
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        recommendationsDisksPost: async (instance: TypesDiskRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'instance' is not null or undefined
            assertParamExists('recommendationsDisksPost', 'instance', instance)
            const localVarPath = `/recommendations/disks`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication ApiKeyAuth required
            await setApiKeyToObject(localVarHeaderParameter, "X-API-Key", configuration)

            // authentication BearerAuth required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(instance, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Get recommendations for compute instances (Recommendations, InstancePricing, VM, Savings)
         * @summary Get recommendations for compute instances
         * @param {TypesComputeRequest} instance Instance
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        recommendationsPost: async (instance: TypesComputeRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'instance' is not null or undefined
            assertParamExists('recommendationsPost', 'instance', instance)
            const localVarPath = `/recommendations`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication ApiKeyAuth required
            await setApiKeyToObject(localVarHeaderParameter, "X-API-Key", configuration)

            // authentication BearerAuth required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(instance, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * DefaultApi - functional programming interface
 */
export const DefaultApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = DefaultApiAxiosParamCreator(configuration)
    return {
        /**
         * Health check endpoint
         * @summary Health check endpoint
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async healthzGet(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<{ [key: string]: string; }>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.healthzGet(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.healthzGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Delete a custom provider instance
         * @summary Delete a custom provider instance
         * @param {string} id Instance ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async marketplaceProvidersComputeDelete(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<TypesCustomPricingResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.marketplaceProvidersComputeDelete(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.marketplaceProvidersComputeDelete']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Get your custom pricing entries
         * @summary Get your custom pricing entries
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async marketplaceProvidersComputeGet(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<TypesMarketplaceProvidersResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.marketplaceProvidersComputeGet(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.marketplaceProvidersComputeGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Register a custom provider
         * @summary Register a custom provider
         * @param {TypesCustomPriceRequest} instance Custom pricing request
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async marketplaceProvidersComputePost(instance: TypesCustomPriceRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<TypesCustomPricingResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.marketplaceProvidersComputePost(instance, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.marketplaceProvidersComputePost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Delete a custom disk provider entry
         * @summary Delete a custom disk provider entry
         * @param {string} id Disk pricing ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async marketplaceProvidersDisksDelete(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<TypesCustomDiskPricingResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.marketplaceProvidersDisksDelete(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.marketplaceProvidersDisksDelete']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Get your custom disk pricing entries
         * @summary Get your custom disk pricing entries
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async marketplaceProvidersDisksGet(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<TypesMarketplaceDiskProvidersResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.marketplaceProvidersDisksGet(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.marketplaceProvidersDisksGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Register a custom disk provider
         * @summary Register a custom disk provider
         * @param {TypesCustomDiskPriceRequest} instance Custom disk pricing request
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async marketplaceProvidersDisksPost(instance: TypesCustomDiskPriceRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<TypesCustomDiskPricingResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.marketplaceProvidersDisksPost(instance, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.marketplaceProvidersDisksPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Get pricing for compute instances
         * @summary Get pricing for an instance
         * @param {GithubComBaselinehqGolangSharedTypesInstance} instance Instance
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async pricingComputePost(instance: GithubComBaselinehqGolangSharedTypesInstance, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<SchemaComputePricingsRow>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.pricingComputePost(instance, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.pricingComputePost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Get pricing for a disk
         * @summary Get pricing for a disk
         * @param {TypesDisk} instance Disk
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async pricingDisksPost(instance: TypesDisk, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<SchemaDiskPricingsRow>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.pricingDisksPost(instance, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.pricingDisksPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Get pricing for compute instances
         * @summary Get pricing for an instance
         * @param {GithubComBaselinehqGolangSharedTypesInstance} instance Instance
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async pricingPost(instance: GithubComBaselinehqGolangSharedTypesInstance, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<SchemaComputePricingsRow>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.pricingPost(instance, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.pricingPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Get details for the providers
         * @summary Get details for the providers
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async providersGet(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<{ [key: string]: ProviderConfig; }>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.providersGet(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.providersGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Get recommendations for compute instances (Recommendations, InstancePricing, VM, Savings)
         * @summary Get recommendations for compute instances
         * @param {TypesComputeRequest} instance Instance
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async recommendationsComputePost(instance: TypesComputeRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<{ [key: string]: Array<TypesComputeResultsValueInner>; }>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.recommendationsComputePost(instance, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.recommendationsComputePost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Get recommendations for disks used in the server (Recommendations, DiskPricing, Savings)
         * @summary Get recommendations for disks
         * @param {TypesDiskRequest} instance Instance
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async recommendationsDisksPost(instance: TypesDiskRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<{ [key: string]: Array<TypesDiskResultsValueInner>; }>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.recommendationsDisksPost(instance, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.recommendationsDisksPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Get recommendations for compute instances (Recommendations, InstancePricing, VM, Savings)
         * @summary Get recommendations for compute instances
         * @param {TypesComputeRequest} instance Instance
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async recommendationsPost(instance: TypesComputeRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<{ [key: string]: Array<TypesComputeResultsValueInner>; }>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.recommendationsPost(instance, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.recommendationsPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * DefaultApi - factory interface
 */
export const DefaultApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = DefaultApiFp(configuration)
    return {
        /**
         * Health check endpoint
         * @summary Health check endpoint
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        healthzGet(options?: RawAxiosRequestConfig): AxiosPromise<{ [key: string]: string; }> {
            return localVarFp.healthzGet(options).then((request) => request(axios, basePath));
        },
        /**
         * Delete a custom provider instance
         * @summary Delete a custom provider instance
         * @param {DefaultApiMarketplaceProvidersComputeDeleteRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        marketplaceProvidersComputeDelete(requestParameters: DefaultApiMarketplaceProvidersComputeDeleteRequest, options?: RawAxiosRequestConfig): AxiosPromise<TypesCustomPricingResponse> {
            return localVarFp.marketplaceProvidersComputeDelete(requestParameters.id, options).then((request) => request(axios, basePath));
        },
        /**
         * Get your custom pricing entries
         * @summary Get your custom pricing entries
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        marketplaceProvidersComputeGet(options?: RawAxiosRequestConfig): AxiosPromise<TypesMarketplaceProvidersResponse> {
            return localVarFp.marketplaceProvidersComputeGet(options).then((request) => request(axios, basePath));
        },
        /**
         * Register a custom provider
         * @summary Register a custom provider
         * @param {DefaultApiMarketplaceProvidersComputePostRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        marketplaceProvidersComputePost(requestParameters: DefaultApiMarketplaceProvidersComputePostRequest, options?: RawAxiosRequestConfig): AxiosPromise<TypesCustomPricingResponse> {
            return localVarFp.marketplaceProvidersComputePost(requestParameters.instance, options).then((request) => request(axios, basePath));
        },
        /**
         * Delete a custom disk provider entry
         * @summary Delete a custom disk provider entry
         * @param {DefaultApiMarketplaceProvidersDisksDeleteRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        marketplaceProvidersDisksDelete(requestParameters: DefaultApiMarketplaceProvidersDisksDeleteRequest, options?: RawAxiosRequestConfig): AxiosPromise<TypesCustomDiskPricingResponse> {
            return localVarFp.marketplaceProvidersDisksDelete(requestParameters.id, options).then((request) => request(axios, basePath));
        },
        /**
         * Get your custom disk pricing entries
         * @summary Get your custom disk pricing entries
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        marketplaceProvidersDisksGet(options?: RawAxiosRequestConfig): AxiosPromise<TypesMarketplaceDiskProvidersResponse> {
            return localVarFp.marketplaceProvidersDisksGet(options).then((request) => request(axios, basePath));
        },
        /**
         * Register a custom disk provider
         * @summary Register a custom disk provider
         * @param {DefaultApiMarketplaceProvidersDisksPostRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        marketplaceProvidersDisksPost(requestParameters: DefaultApiMarketplaceProvidersDisksPostRequest, options?: RawAxiosRequestConfig): AxiosPromise<TypesCustomDiskPricingResponse> {
            return localVarFp.marketplaceProvidersDisksPost(requestParameters.instance, options).then((request) => request(axios, basePath));
        },
        /**
         * Get pricing for compute instances
         * @summary Get pricing for an instance
         * @param {DefaultApiPricingComputePostRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        pricingComputePost(requestParameters: DefaultApiPricingComputePostRequest, options?: RawAxiosRequestConfig): AxiosPromise<SchemaComputePricingsRow> {
            return localVarFp.pricingComputePost(requestParameters.instance, options).then((request) => request(axios, basePath));
        },
        /**
         * Get pricing for a disk
         * @summary Get pricing for a disk
         * @param {DefaultApiPricingDisksPostRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        pricingDisksPost(requestParameters: DefaultApiPricingDisksPostRequest, options?: RawAxiosRequestConfig): AxiosPromise<SchemaDiskPricingsRow> {
            return localVarFp.pricingDisksPost(requestParameters.instance, options).then((request) => request(axios, basePath));
        },
        /**
         * Get pricing for compute instances
         * @summary Get pricing for an instance
         * @param {DefaultApiPricingPostRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        pricingPost(requestParameters: DefaultApiPricingPostRequest, options?: RawAxiosRequestConfig): AxiosPromise<SchemaComputePricingsRow> {
            return localVarFp.pricingPost(requestParameters.instance, options).then((request) => request(axios, basePath));
        },
        /**
         * Get details for the providers
         * @summary Get details for the providers
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        providersGet(options?: RawAxiosRequestConfig): AxiosPromise<{ [key: string]: ProviderConfig; }> {
            return localVarFp.providersGet(options).then((request) => request(axios, basePath));
        },
        /**
         * Get recommendations for compute instances (Recommendations, InstancePricing, VM, Savings)
         * @summary Get recommendations for compute instances
         * @param {DefaultApiRecommendationsComputePostRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        recommendationsComputePost(requestParameters: DefaultApiRecommendationsComputePostRequest, options?: RawAxiosRequestConfig): AxiosPromise<{ [key: string]: Array<TypesComputeResultsValueInner>; }> {
            return localVarFp.recommendationsComputePost(requestParameters.instance, options).then((request) => request(axios, basePath));
        },
        /**
         * Get recommendations for disks used in the server (Recommendations, DiskPricing, Savings)
         * @summary Get recommendations for disks
         * @param {DefaultApiRecommendationsDisksPostRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        recommendationsDisksPost(requestParameters: DefaultApiRecommendationsDisksPostRequest, options?: RawAxiosRequestConfig): AxiosPromise<{ [key: string]: Array<TypesDiskResultsValueInner>; }> {
            return localVarFp.recommendationsDisksPost(requestParameters.instance, options).then((request) => request(axios, basePath));
        },
        /**
         * Get recommendations for compute instances (Recommendations, InstancePricing, VM, Savings)
         * @summary Get recommendations for compute instances
         * @param {DefaultApiRecommendationsPostRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        recommendationsPost(requestParameters: DefaultApiRecommendationsPostRequest, options?: RawAxiosRequestConfig): AxiosPromise<{ [key: string]: Array<TypesComputeResultsValueInner>; }> {
            return localVarFp.recommendationsPost(requestParameters.instance, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * DefaultApi - interface
 */
export interface DefaultApiInterface {
    /**
     * Health check endpoint
     * @summary Health check endpoint
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    healthzGet(options?: RawAxiosRequestConfig): AxiosPromise<{ [key: string]: string; }>;

    /**
     * Delete a custom provider instance
     * @summary Delete a custom provider instance
     * @param {DefaultApiMarketplaceProvidersComputeDeleteRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    marketplaceProvidersComputeDelete(requestParameters: DefaultApiMarketplaceProvidersComputeDeleteRequest, options?: RawAxiosRequestConfig): AxiosPromise<TypesCustomPricingResponse>;

    /**
     * Get your custom pricing entries
     * @summary Get your custom pricing entries
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    marketplaceProvidersComputeGet(options?: RawAxiosRequestConfig): AxiosPromise<TypesMarketplaceProvidersResponse>;

    /**
     * Register a custom provider
     * @summary Register a custom provider
     * @param {DefaultApiMarketplaceProvidersComputePostRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    marketplaceProvidersComputePost(requestParameters: DefaultApiMarketplaceProvidersComputePostRequest, options?: RawAxiosRequestConfig): AxiosPromise<TypesCustomPricingResponse>;

    /**
     * Delete a custom disk provider entry
     * @summary Delete a custom disk provider entry
     * @param {DefaultApiMarketplaceProvidersDisksDeleteRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    marketplaceProvidersDisksDelete(requestParameters: DefaultApiMarketplaceProvidersDisksDeleteRequest, options?: RawAxiosRequestConfig): AxiosPromise<TypesCustomDiskPricingResponse>;

    /**
     * Get your custom disk pricing entries
     * @summary Get your custom disk pricing entries
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    marketplaceProvidersDisksGet(options?: RawAxiosRequestConfig): AxiosPromise<TypesMarketplaceDiskProvidersResponse>;

    /**
     * Register a custom disk provider
     * @summary Register a custom disk provider
     * @param {DefaultApiMarketplaceProvidersDisksPostRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    marketplaceProvidersDisksPost(requestParameters: DefaultApiMarketplaceProvidersDisksPostRequest, options?: RawAxiosRequestConfig): AxiosPromise<TypesCustomDiskPricingResponse>;

    /**
     * Get pricing for compute instances
     * @summary Get pricing for an instance
     * @param {DefaultApiPricingComputePostRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    pricingComputePost(requestParameters: DefaultApiPricingComputePostRequest, options?: RawAxiosRequestConfig): AxiosPromise<SchemaComputePricingsRow>;

    /**
     * Get pricing for a disk
     * @summary Get pricing for a disk
     * @param {DefaultApiPricingDisksPostRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    pricingDisksPost(requestParameters: DefaultApiPricingDisksPostRequest, options?: RawAxiosRequestConfig): AxiosPromise<SchemaDiskPricingsRow>;

    /**
     * Get pricing for compute instances
     * @summary Get pricing for an instance
     * @param {DefaultApiPricingPostRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    pricingPost(requestParameters: DefaultApiPricingPostRequest, options?: RawAxiosRequestConfig): AxiosPromise<SchemaComputePricingsRow>;

    /**
     * Get details for the providers
     * @summary Get details for the providers
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    providersGet(options?: RawAxiosRequestConfig): AxiosPromise<{ [key: string]: ProviderConfig; }>;

    /**
     * Get recommendations for compute instances (Recommendations, InstancePricing, VM, Savings)
     * @summary Get recommendations for compute instances
     * @param {DefaultApiRecommendationsComputePostRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    recommendationsComputePost(requestParameters: DefaultApiRecommendationsComputePostRequest, options?: RawAxiosRequestConfig): AxiosPromise<{ [key: string]: Array<TypesComputeResultsValueInner>; }>;

    /**
     * Get recommendations for disks used in the server (Recommendations, DiskPricing, Savings)
     * @summary Get recommendations for disks
     * @param {DefaultApiRecommendationsDisksPostRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    recommendationsDisksPost(requestParameters: DefaultApiRecommendationsDisksPostRequest, options?: RawAxiosRequestConfig): AxiosPromise<{ [key: string]: Array<TypesDiskResultsValueInner>; }>;

    /**
     * Get recommendations for compute instances (Recommendations, InstancePricing, VM, Savings)
     * @summary Get recommendations for compute instances
     * @param {DefaultApiRecommendationsPostRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    recommendationsPost(requestParameters: DefaultApiRecommendationsPostRequest, options?: RawAxiosRequestConfig): AxiosPromise<{ [key: string]: Array<TypesComputeResultsValueInner>; }>;

}

/**
 * Request parameters for marketplaceProvidersComputeDelete operation in DefaultApi.
 */
export interface DefaultApiMarketplaceProvidersComputeDeleteRequest {
    /**
     * Instance ID
     */
    readonly id: string
}

/**
 * Request parameters for marketplaceProvidersComputePost operation in DefaultApi.
 */
export interface DefaultApiMarketplaceProvidersComputePostRequest {
    /**
     * Custom pricing request
     */
    readonly instance: TypesCustomPriceRequest
}

/**
 * Request parameters for marketplaceProvidersDisksDelete operation in DefaultApi.
 */
export interface DefaultApiMarketplaceProvidersDisksDeleteRequest {
    /**
     * Disk pricing ID
     */
    readonly id: string
}

/**
 * Request parameters for marketplaceProvidersDisksPost operation in DefaultApi.
 */
export interface DefaultApiMarketplaceProvidersDisksPostRequest {
    /**
     * Custom disk pricing request
     */
    readonly instance: TypesCustomDiskPriceRequest
}

/**
 * Request parameters for pricingComputePost operation in DefaultApi.
 */
export interface DefaultApiPricingComputePostRequest {
    /**
     * Instance
     */
    readonly instance: GithubComBaselinehqGolangSharedTypesInstance
}

/**
 * Request parameters for pricingDisksPost operation in DefaultApi.
 */
export interface DefaultApiPricingDisksPostRequest {
    /**
     * Disk
     */
    readonly instance: TypesDisk
}

/**
 * Request parameters for pricingPost operation in DefaultApi.
 */
export interface DefaultApiPricingPostRequest {
    /**
     * Instance
     */
    readonly instance: GithubComBaselinehqGolangSharedTypesInstance
}

/**
 * Request parameters for recommendationsComputePost operation in DefaultApi.
 */
export interface DefaultApiRecommendationsComputePostRequest {
    /**
     * Instance
     */
    readonly instance: TypesComputeRequest
}

/**
 * Request parameters for recommendationsDisksPost operation in DefaultApi.
 */
export interface DefaultApiRecommendationsDisksPostRequest {
    /**
     * Instance
     */
    readonly instance: TypesDiskRequest
}

/**
 * Request parameters for recommendationsPost operation in DefaultApi.
 */
export interface DefaultApiRecommendationsPostRequest {
    /**
     * Instance
     */
    readonly instance: TypesComputeRequest
}

/**
 * DefaultApi - object-oriented interface
 */
export class DefaultApi extends BaseAPI implements DefaultApiInterface {
    /**
     * Health check endpoint
     * @summary Health check endpoint
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public healthzGet(options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).healthzGet(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Delete a custom provider instance
     * @summary Delete a custom provider instance
     * @param {DefaultApiMarketplaceProvidersComputeDeleteRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public marketplaceProvidersComputeDelete(requestParameters: DefaultApiMarketplaceProvidersComputeDeleteRequest, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).marketplaceProvidersComputeDelete(requestParameters.id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Get your custom pricing entries
     * @summary Get your custom pricing entries
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public marketplaceProvidersComputeGet(options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).marketplaceProvidersComputeGet(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Register a custom provider
     * @summary Register a custom provider
     * @param {DefaultApiMarketplaceProvidersComputePostRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public marketplaceProvidersComputePost(requestParameters: DefaultApiMarketplaceProvidersComputePostRequest, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).marketplaceProvidersComputePost(requestParameters.instance, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Delete a custom disk provider entry
     * @summary Delete a custom disk provider entry
     * @param {DefaultApiMarketplaceProvidersDisksDeleteRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public marketplaceProvidersDisksDelete(requestParameters: DefaultApiMarketplaceProvidersDisksDeleteRequest, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).marketplaceProvidersDisksDelete(requestParameters.id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Get your custom disk pricing entries
     * @summary Get your custom disk pricing entries
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public marketplaceProvidersDisksGet(options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).marketplaceProvidersDisksGet(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Register a custom disk provider
     * @summary Register a custom disk provider
     * @param {DefaultApiMarketplaceProvidersDisksPostRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public marketplaceProvidersDisksPost(requestParameters: DefaultApiMarketplaceProvidersDisksPostRequest, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).marketplaceProvidersDisksPost(requestParameters.instance, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Get pricing for compute instances
     * @summary Get pricing for an instance
     * @param {DefaultApiPricingComputePostRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public pricingComputePost(requestParameters: DefaultApiPricingComputePostRequest, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).pricingComputePost(requestParameters.instance, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Get pricing for a disk
     * @summary Get pricing for a disk
     * @param {DefaultApiPricingDisksPostRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public pricingDisksPost(requestParameters: DefaultApiPricingDisksPostRequest, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).pricingDisksPost(requestParameters.instance, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Get pricing for compute instances
     * @summary Get pricing for an instance
     * @param {DefaultApiPricingPostRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public pricingPost(requestParameters: DefaultApiPricingPostRequest, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).pricingPost(requestParameters.instance, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Get details for the providers
     * @summary Get details for the providers
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public providersGet(options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).providersGet(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Get recommendations for compute instances (Recommendations, InstancePricing, VM, Savings)
     * @summary Get recommendations for compute instances
     * @param {DefaultApiRecommendationsComputePostRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public recommendationsComputePost(requestParameters: DefaultApiRecommendationsComputePostRequest, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).recommendationsComputePost(requestParameters.instance, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Get recommendations for disks used in the server (Recommendations, DiskPricing, Savings)
     * @summary Get recommendations for disks
     * @param {DefaultApiRecommendationsDisksPostRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public recommendationsDisksPost(requestParameters: DefaultApiRecommendationsDisksPostRequest, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).recommendationsDisksPost(requestParameters.instance, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Get recommendations for compute instances (Recommendations, InstancePricing, VM, Savings)
     * @summary Get recommendations for compute instances
     * @param {DefaultApiRecommendationsPostRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public recommendationsPost(requestParameters: DefaultApiRecommendationsPostRequest, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).recommendationsPost(requestParameters.instance, options).then((request) => request(this.axios, this.basePath));
    }
}



